version: '3.3'

services:
  wordpress:
    container_name: "publisher_wordpress"
    image: "wordpress:${WORDPRESS-5.4-php7.2}"
    ports:
      - 8080:80
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ..:/var/www/html/wp-content/plugins/podlove-podcasting-plugin-for-wordpress
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DB_PASSWORD: "do not use for production"
    depends_on:
      - mysql

  mysql:
    container_name: "publisher_database"
    image: "mariadb:${DATABASE-10.4}"
    environment:
      MYSQL_ROOT_PASSWORD: "do not use for production"
