on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*-beta*'

name: Beta Release

jobs:
  build:
    name: Build and Release Beta Version
    runs-on: ubuntu-24.04
    steps:
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build project
        env:
          TAG_NAME: ${{ github.ref }}
        run: |
          make install_php_scoper
          make build
          mv dist podlove-podcasting-plugin-for-wordpress
          zip -r podlove-podcasting-plugin-for-wordpress.zip podlove-podcasting-plugin-for-wordpress
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            podlove-podcasting-plugin-for-wordpress.zip
